image: hwrunner:latest
variables:
    GIT_SSL_NO_VERIFY: "true"
    EXEC: bourse
    HW_DIR: hw5
before_script:
    - make clean all -C ${HW_DIR}
stages:
    - build
build:
    stage: build
    script:
        - echo "Build done"
